### ISSUE TITLE
[8193.33] Reloading makes creature bodies have no loot

### ISSUE THREAD

**Issue by Taro94** [Beamdog/nwn-issues#401]
**To Reproduce**

 - Run attached module.
 - Kill the goblin in the room and right after he dies (while he's still dropping to the floor) perform a quicksave.
 - Try to loot the corpse - it will have an ale.
 - Load the quicksave and try to loot the goblin corpse - it will have no items or gold (quicksave with this behavior is also attached).
 

**Specifics**

 - OS: Linux
 - Game build: 8193.33
 - Distro platform: GOG
 - Content overrides: None
 - Regression: No - happens in 1.69, too

[reloadTest.mod.zip](https://github.com/Beamdog/nwn-issues/files/7404405/reloadTest.mod.zip)
[000000 - quicksave.zip](https://github.com/Beamdog/nwn-issues/files/7404407/000000.-.quicksave.zip)

**Comment by Finaldeath** [comment]
@Taro94 I can't seem to reproduce so I think this was fixed. Tested your module and it still has an ale after loading a save. If you have time to test again it'd be welcome.

**Comment by Taro94** [comment]
@Finaldeath Still happening. Have you tried loading the attached save file, too? Does the corpse have the ale in it? In the meantime I'll see how it works with Windows binaries.

**Comment by Finaldeath** [comment]
I can't account for the quicksave - I didn't test that, since if the save hasn't got the data no amount of fixes will solve it. I could dig into the GFF and look for the placeables inventory.

What I tested was in 36 load the module -> kill the goblin -> check for ale -> save game -> load game -> still has ale.

**Comment by Finaldeath** [comment]
Ok then the code to transfer things to the fake-body-container is probably only run on accessing it, but the save game might not properly save dead creatures inventories or something, hmm.

Difficult to solve potentially since the dead creature could - theoretically - be resurrected and want to keep the items on themselves. Then again who enables lootable, selectable bodies on a creature that can be resurrected? Hmm.
